-- CreateTable
CREATE TABLE "Lead" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    "name" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "phone" TEXT,
    "company" TEXT,
    "persona" TEXT NOT NULL,
    "requestType" TEXT NOT NULL,
    "locationText" TEXT,
    "propertyType" TEXT,
    "sizeSfText" TEXT,
    "budgetText" TEXT,
    "timelineText" TEXT,
    "notes" TEXT,
    "aiLeadType" TEXT,
    "aiLeadScore" INTEGER,
    "aiSummary" TEXT,
    "aiMissingInfo" TEXT,
    "aiNextStep" TEXT,
    "aiFollowUpEmailSubject" TEXT,
    "aiFollowUpEmailBody" TEXT,
    "aiFollowUpText" TEXT,
    "aiModel" TEXT,
    "aiRunAt" DATETIME,
    "rawIntakeJson" TEXT,
    "rawAiJson" TEXT
);
